2003scape/rsc-c

- src/gl/vertex-buffer.c
%lu for printing unsigned ints
> portability fixes: printf usage

- src/chat-message.c
- src/game-data.c
- src/utility.c
compiling on NetBSD warns about this.
while here, remove some code duplication by using strtolower more.
> undefined behaviour: ctype functions must take unsigned char

- src/ui/message-tabs.c
> Fix a stack buffer overflow that occurs whenever chat is sent

- src/surface.c
- src/surface.h
- src/ui/combat-style.c
- src/ui/combat-style.h
>  More compact combat style menu on 3DS 

- src/lib/isaac.c
- src/lib/isaac.h
- src/mudclient.c
- src/mudclient.h
- src/packet-handler.c
- src/packet-stream.c
- src/packet-stream.h
- src/utility.c
- src/utility.h
Closed my previous PR by mistake RIP.
Define `NO_RSA` or `NO_ISAAC` to disable them.
> RSA/ISAAC support + OpenRSC compatibility for 204

- src/ui/status-bars.c
> Add drains/boost to the right of the status UI

- Makefile
- README.md
- src/game-character.h
- src/game-model.h
- src/mudclient.c
- src/mudclient.h
- src/options.h
- src/packet-stream.h
- src/panel.h
- src/polygon.h
- src/scene.h
- src/surface.h
- src/utility.h
- src/world.h
> Mac OS X 10.4 build fixes

- src/mudclient.c
> Fix use of freed NPC/Player data on re-login in status bars.

- src/mudclient.h
- src/packet-handler.c
Inspired by the legacy of the "shifty man".
> More guards against server sending futuristic content.

- src/mudclient.c
- src/packet-handler.c
> Defend against the server sending too many entities

- src/ui/experience-drops.c
> Fix for stack buffer overflow in XP drops

- Makefile.nx
- src/gl/shader.c
Just 2 Small Edits to fix building for Nintendo Switch.
> Fix Switch Build

- src/mudclient.c
- src/options.c
- src/options.h
- src/ui/additional-options.c
> options: Add option to enable/disable light flicker in dungeons

- src/mudclient.h
> Fix duplication of out-of-view entities

- src/game-model.c
- src/mudclient.c
> Fix issues affecting F2P clients

- Makefile
Not super important but I always make this change when compiling on Tiger
> makefile compat with extremely old GCC versions

- src/mudclient.c
- src/options.c
- src/options.h
- src/ui/additional-options.c
> Add option to disable the fog of war

- src/mudclient.c
> Do not attempt to draw mob sprites that haven't loaded

- src/packet-handler.c
> Fix off-by-one in server message box parsing

- Makefile
- src/options.c
> Add VANILLA_IS_DEFAULT compilation option

- src/mudclient.c
- src/options.c
> Diverse NPCs not compatible with OpenGL mode

- src/chat-message.c
- src/game-model.c
- src/mudclient.c
- src/mudclient.h
- src/packet-handler.c
- src/panel.c
- src/surface.c
- src/surface.h
- src/ui/bank.c
- src/ui/login.c
- src/ui/menu.c
- src/ui/message-tabs.c
- src/ui/options-tab.c
- src/ui/social-tab.c
- src/ui/stats-tab.c
- src/ui/transaction.c
- src/utility.c
- src/world.c
Mostly related to assigning the result of strlen to int, but there's a couple of inner for loops that reuse the variable name "i'.
And a year 2038 problem (my favorite!)
> Fix various code quality issues found by lint(1)

- src/custom/diverse-npcs.c
> Diverse NPCs update

- src/options.c
- src/options.h
- src/ui/stats-tab.c
- src/ui/stats-tab.h
- src/ui/status-bars.c
> Emulation of mudclient110 UI for sundae

- .gitignore
- Makefile
- Makefile.emscripten
- Makefile.nx
- Makefile.wii
- Makefile.win9x
- Makefile.windows
- src/lib/rsa/rsa-openssl.c
- src/lib/rsa/rsa-tiny.c
- src/lib/rsa/rsa.h
- src/packet-stream.c
- src/packet-stream.h
> packet-stream: Optionally support RSA encryption using OpenSSL

- src/mudclient.c
- src/mudclient.h
- src/options.c
- src/options.h
- src/packet-stream.c
- src/ui/additional-options.c
- src/ui/login.c
- src/ui/login.h
- src/ui/worldlist.c
- src/ui/worldlist.h
- src/utility.c
- src/utility.h
> Add world selection support

- src/utility.c
> utility: fix storing all settings in worlds.cfg on windows

- src/mudclient.h
> mudclient: Fix large stacks overflowing offer-x menu

- Makefile.3ds
- src/mudclient.c
- src/mudclient.h
- src/panel.h
- src/scene-3ds-gl.c
- src/surface.c
- src/ui/additional-options.c
- src/ui/login.c
Still need to look at #245 or the sprites are all wrong but this fixes the build problems and it no longer crashes
> Fix 3DS regressions since December 2023
