Makefile, Makefile.windows, README.md, src/game-model.h, src/mudclient.h, src/scene.h, src/utility.h, src/world.h
use pkg-config to find dependencies on Unix, helps when things are installed outside of core system directories on e.g. BSD/others
note SDL2_image dependency for GL
=> portability: overhaul dependency handling

src/world.c
New code matches authentic code.
Found by `-fsanitize=undefined`.
=> Fix off-by-one out of bounds array access in world.c.

src/game-model.c, src/game-model.h, src/mudclient.c, src/utility.c, src/utility.h
Fixes a couple of warnings from `-fsanitize=undefiend`. Still too much signed overflow in scene.c/surface.c to be okay without `-fwrapv`.
=> Fix some signed overflow / constness issues in archive decoding

Makefile
There is way too much code that assumes that signed overflow wraps like Java. Many of these data types can eventually be converted to unsigned (or overflow checks added in some cases).
With this change and the `world.c` out of bounds access fixed, the code is clean for`-fsanitize=undefined` when connected to a trustworthy server.
=> Enable -fwrapv so signed overflow is defined to wrap.

src/mudclient.c, src/options.c, src/options.h, src/ui/additional-options.c, src/ui/shop.c
Matches the way the authentic trade screen works (and reuses the same code). For protocols before 205, we can't specify a number to sell/buy so this sends one packet per frame. Basically saves fingers when spam clicking and puts the client more on par with ~235 based clients that have "buy/sell X".
=> Option to allow holding the mouse button down to buy/sell from shops in bulk

src/game-character.c
Initialize npc_id to -1 when Characters are created.
=> Fix "you are currently attacking a unicorn" for PvP combat

src/mudclient.c, src/mudclient.h
Keeps the amount of fog in the distance at roughly "authentic-feeling" levels.
=> Adjust fog when the client is resized

src/surface.c
The bar can exceed the bounds of the box when a player has raised Prayer due to praying at the monastery or using a Potion of Zamorak.
Before:
After:
(Ignore the right of the image and focus on the left.)
=> Fix status bars when current level exceeds base.

cache/flat.gl2.fs, cache/flat.gl2.vs, cache/game-model.gl2.fs, cache/game-model.gl2.vs, src/gl/shader.c, src/gl/vertex-buffer.c, src/mudclient.c, src/scene.c, src/surface.c
Adds more OpenGL rendering options.
OpenGL 1.5 provided the following extensions are available.
GL_ARB_shading_language_100, GL_ARB_vertex_shader, GL_ARB_fragment_shader, GL_ARB_shader_objects.
Used this "OpenGL 1.5 to OpenGL 2.0 GLSL Migration Guide" in reverse as reference.
https://www.yaldex.com/open-gl/app02lev1sec35.html
OpenGL 2.0 only needs core.
=> Support OpenGL 1.5 and 2.0

src/packet-stream.c, src/packet-stream.h
Helps running on platforms that don't have POSIX 2008 and therefore lack send(). Platforms that remain supported that have this restriction include Solaris 10, and probably OpenServer/UnixWare but my VM is currently broken so I can't check. Perhaps more importantly I need this on PowerPC Mac OS X.
Disconnection and reconnection when the server exits function normally.
=> Install handler to ignore SIGPIPE rather than using send(2)

src/mudclient.c, src/options.c, src/options.h, src/ui/additional-options.c, src/ui/menu.c, src/ui/menu.h
Adds the ability to enable/disable hover tooltips for the current action your move is hovering over. Example image:
https://i.imgur.com/6ZNu6GR.png
=> add hover tooltip

src/mudclient.c
There is no support for callback-based audio in the code, which all earlier versions (including SDL 1.2) require.
=> Limit audio initialization to SDL 2.0.4 and newer.

src/mudclient.c, src/version.h, src/world.c, src/world.h
2001 .jm format maps, here showing Ghost Town:
2002-2003 mid-format .dats (newly discovered due to this change! Will document shortly).
Showing Varrock before Biohazard.
=> Support for legacy map file formats

src/utility.c
=> Simplify hash_file_name()

src/packet-handler.c
Do not allow the server arrays to be overrun.
=> Reject excessively high NPC/player server indicies

src/custom/item-highlight.c, src/custom/item-highlight.h, src/mudclient.c, src/mudclient.h, src/options.c, src/options.h
Adds an option to add text labels for valuable ground items, such as those on the rare drop table, or rare runes.
Closes #48
=> Add ground item highlight text

src/mudclient.c, src/mudclient.h, src/options.c, src/surface.c, src/surface.h, src/ui/additional-options.c, src/ui/additional-options.h, src/ui/experience-drops.c, src/ui/magic-tab.c, src/ui/magic-tab.h, src/ui/menu.c, src/ui/menu.h, src/ui/social-tab.c, src/ui/social-tab.h, src/ui/stats-tab.c, src/ui/stats-tab.h, src/ui/transaction.c, src/utility.c, src/utility.h
- Simplifies the mobile code since no more custom calculations are needed for the additional options UI.
- "Server" tab renamed to "game", has more options that affect custom content and fundamentals.
- "Display" tab renamed to "UI".
- Text made slightly more compact.
- Height increased (still fits 3DS).
- Add missing options to the menu, fix TGA sprites option to work as expected (valid range should not be 0, 0)
=> Space for more additional options (+more constification)

src/packet-handler.c
By doing this we reduce the line count (by removing code that copies every field in a struct) and provide better hints to the compiler about what our goals are.
The Ultimate Test™ (going up and down ladders in falador) passes. Should not be any functional change.
=> packet-handler: refactor: change implicit copies into explicit ones

src/mudclient.c, src/packet-handler.c, src/ui/login.c, src/world.c, src/world.h
The following functions were renamed:
```
world_load_section_from3 -> world_load_section
world_remove_object2 -> world_register_object
world_set_object_adjacency_from4 -> world_register_wall_object
world_set_object_adjacency_from3 -> world_set_blocked
world_method407 -> world_set_unblocked
world_method425 -> world_vertex_shadow
world_method404 -> world_update_shadow_rect
world_get_tile_decoration_from4 -> world_decoration_or_colour
world_load_section_from4 -> world_load_assemble
world_set_tiles -> world_fill_edges
```
=> world: Refactor, rename unrenamed functions, resolve various TODOs.

src/game-model.c
While here, fix an apparent bug where the transformation arrays were copied even if their pointers were identical (with autocommit) or null, found by the undefined behaviour sanitizer which triggered after the memcpy conversion.
=> game-model: Use memcpy to copy transformation arrays.

src/custom/clarify-herblaw-items.c, src/game-data.c, src/mudclient.h, src/packet-stream.c, src/packet-stream.h, src/surface.c, src/surface.h, src/ui/additional-options.c, src/ui/additional-options.h, src/ui/bank.c, src/ui/duel.c, src/ui/stats-tab.c, src/ui/stats-tab.h, src/ui/ui-tabs.c, src/utility.c, src/utility.h, src/world.c, src/world.h
Some of this is C99 compliance stuff, e.g. declaring functions with () for empty arguments is deprecated.
=> Fix issues found by -Wstrict-prototypes -Wmissing-prototypes

src/scene.c, src/scene.h
```
scene_texture_scanline -> scene_texture128_scanline
scene_texture_back_translucent_scanline -> scene_texture128_alphakey_scanline
scene_texture_scanline2 -> scene_texture64_scanline
scene_texture_back_translucent_scanline2 -> scene_texture64_alphakey_scanline
scene_gradient_translucent_scanline -> scene_colour_translucent_scanline
scene_gradient_scanline -> scene_colour_scanline
```
Why not "gradient"? The gradient is mostly a product of the gouraud
shading, which is controlled separately.
=> scene: Rename scanline rasterization functions, sprinkle static/restric

Makefile.win9x, README.md
Changes the makefile to properly target a Pentium Pro and updated the readme.
=> Win9X Requires a Pentium Pro

src/world.c
Also use memset when clearing .hei maps instead of manual loops.
=> Properly clear missing regions when loading JM maps

src/ui/additional-options.c
"Certificate items" was accidentally duplicated during a merge.
Ideas for future: merge total/remaining XP options (they both need to increase the height of the skills menu beyond vanilla)
=> Fix additional options overflowing the interface again

src/mudclient.c
Here they are digital button press events rather than analogue scroll events.
=> SDL 1.2 mouse wheel scrolling

src/options.c
Right now it changes whether it's a F2P client or not, which is not what we want.
=> Fix registration option.

src/mudclient.c
Use SDL's built-in mechanism for this.
Resolves the remaining SDL 1.2 input issues, so closes #145
XXX we could also do this separately for SDL2 by using SDL_TEXTINPUT events (according to https://wiki.libsdl.org/SDL2/MigrationGuide)
=> SDL12: Rework/simplify key to character conversion

src/options.c
- Disable 3D ground items by default
- Disable certificate items by default
- Disable compass menus by default (allow clicking thru it to walk)
=> Closer-to-vanilla experience by default

src/mudclient.c, src/utility.c
Found by Clang 16 on NetBSD; -Wchar-subscripts
=> Fix use of regular char type with ctype functions

src/mudclient.c, src/mudclient.h, src/scene.c, src/scene.h, src/ui/inventory-tab.c, src/ui/menu.c, src/ui/menu.h, src/ui/minimap-tab.c, src/ui/offer-x.c, src/ui/transaction.c
Menus display more options when the screen is bigger, but the correct number of "more options" is always disabled (even in Catherby on RSC Uranium, where there can be thousands of fish dropped on the floor).
The size of large menus (those that exceed the maximum screen size) is properly calculated by stopping the starting position from being lower than zero.
=> menu: Refactor, allow menus and "more options" to exceed the maximum of 19.

src/mudclient.h
src/ui/offer-x.c does some magic with negative values to encode a value, which I was not expecting. Support negative menu "indices" in the struct.
Closes #171
Closes #170
=> Fix Offer-X after menus refactor

src/ui/options-tab.c
Reuse the "sound effects" space for "additional options".
=> options-tab: In F2P mode, preserve original height.

src/mudclient.c
Use case: Windows XP VM with no drivers installed.
=> mudclient: Make failing to open the audio device non-fatal.

src/mudclient-sdl2.c
Setting this [flag](https://wiki.libsdl.org/SDL2/SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH) allows for mouse clicks events to pass through when focusing an SDL window.
This seemed to work "on my machine" (macOS ARM), but I'm not sure if this is comprehensive as far as all build types, etc. Apologies if this is not the case, and hopefully the maintainers can see the idea through to completion if necessary.
=> Allow focus click passthrough

src/mudclient-sdl.c, src/mudclient-sdl2.c, src/mudclient.h
Rework the keyboard input code to use it, eliminating issues with different keyboard layouts and so on.
Also tested on SDL 1.2 with no changes there.
=> Add support for SDL2 SDL_TEXTINPUT events

src/mudclient.c
The adaption to use SDL_TEXTINPUT means that the number keys are being "pressed" twice (since they have ASCII representation), so they don't get released properly.
Stop them from being "pressed" twice by only recognizing option menu key down inside an option menu.
=> Fix option menu keys getting stuck down.

src/mudclient.c, src/options.c, src/options.h, src/ui/additional-options.c, src/ui/inventory-tab.c, src/ui/magic-tab.c, src/ui/message-tabs.c, src/ui/minimap-tab.c, src/ui/options-tab.c, src/ui/social-tab.c, src/ui/stats-tab.c, src/ui/ui-tabs.c, src/version.h, src/world.c, src/world.h
This is the first steps towards supporting OpenRSC and Sundae with the same binary. In the process, we remove a lot of `#ifdef`, making the code less ugly to read.
=> Support runtime configuration of .jag/.mem versions
